grafana:
  service:
    type: NodePort
    port: 80
    targetPort: 3000
    nodePort: 30060

  adminUser: admin
  adminPassword: admin123

  sidecar:
    datasources:
      enabled: true
      label: app.kubernetes.io/instance
      labelValue: monitoring-grafana
      searchNamespace: monitoring
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: monitoring

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
