apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-grafana-datasources
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: monitoring-grafana
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://monitoring-prometheus-server.monitoring.svc.cluster.local
        isDefault: true
        editable: true
