apiVersion: apps/v1
kind: Deployment
metadata:
  name: mission-status
  labels:
    app: mission-status
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mission-status
  template:
    metadata:
      labels:
        app: mission-status
    spec:
      containers:
        - name: mission-status-container
          image: arkinfotech24/mission-status-app:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
