replicaCount: 2

image:
  repository: arkinfotech24/mission-status-app
    #repository: mission-status
    #tag: "1.0"
  tag: "alpine"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080
