apiVersion: apps/v1
kind: Deployment
metadata:
  name: mission-status
  labels:
    app: mission-status
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mission-status
  template:
    metadata:
      labels:
        app: mission-status
    spec:
      containers:
        - name: mission-status
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
